package com.xisnd.monitoring.event;

public enum EventType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    FILE_UPLOADED,
    FILE_DELETED,
    ANALYSIS_STARTED,
    ANALYSIS_COMPLETED,
    ANALYSIS_FAILED,
    AGENT_REGISTERED,
    AGENT_DELETED,
    AGENT_CONNECTED,
    AGENT_DISCONNECTED,
    INCIDENT_OPENED,
    INCIDENT_RESOLVED,
    ALERT_SENT,
    ALERT_FAILED
}
