const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');const assert=require('node:assert/strict');
const root=process.cwd();const git=(...args)=>cp.execFileSync('git',['-c',`safe.directory=${root.replaceAll('\\','/')}`,...args],{encoding:'utf8'}).trim();
const sourceFiles=git('ls-files').split('\n');
const protectedGroups=['frontend/tailwind.config.ts','frontend/src/shared/ui/','frontend/src/widgets/layout/','backend/build.gradle','backend/settings.gradle','backend/gradle/'];
const changed=git('diff','8d4d5ce','--name-only').split('\n');const protectedChanges=changed.filter(f=>protectedGroups.some(p=>f===p||f.startsWith(p)));assert.equal(protectedChanges.length,0);
const patterns=[{name:'OpenAI key',regex:/\bsk-[A-Za-z0-9_-]{24,}/},{name:'JWT literal',regex:/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{15,}\.[A-Za-z0-9_-]{15,}/},{name:'Agent credential',regex:/\bagt_[A-Za-z0-9_-]{24,}/},{name:'Slack webhook',regex:/https:\/\/hooks\.slack\.com\/services\/[A-Za-z0-9]{8,}\/[A-Za-z0-9]{8,}\/[A-Za-z0-9]{15,}/}];
const findings=[];let textFilesScanned=0;for(const file of sourceFiles){if(!fs.existsSync(file)||/\.(png|ico|pdf|docx|xlsx|zip|woff2|ttf|jar)$/.test(file))continue;textFilesScanned++;const contents=fs.readFileSync(file,'utf8');for(const p of patterns)if(p.regex.test(contents))findings.push({file,type:p.name});}
const logFindings=[];for(const file of fs.readdirSync('.demo/logs')){const f=path.join('.demo/logs',file);if(!fs.statSync(f).isFile())continue;const contents=fs.readFileSync(f,'utf8');for(const p of patterns)if(p.regex.test(contents))logFindings.push({file,type:p.name});}
const result={sourceBaseline:'8d4d5ce',trackedFilesListed:sourceFiles.length,textFilesScanned,protectedDesignAndBuildChanges:protectedChanges,credentialPatternMatches:findings,runtimeLogCredentialPatternMatches:logFindings,openAiKeyPresent:Boolean(process.env.OPENAI_API_KEY),note:'Pattern scan checks likely credential literals without printing matched values; does not prove absence of every possible secret.'};
fs.writeFileSync('docs/evidence/static.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));assert.equal(findings.length,0);assert.equal(logFindings.length,0);
